### ISSUE TITLE
Meeting Agenda for 2022-05-06

### ISSUE THREAD

**Issue by jennifer-hoang** [bcgov/opho-cdr-shiny#10]
## Agenda Items:
- [x] Proposal slides (15 min)
  - [x] Dashboard Design (Jessie/Irene)
  - [x] Spatial-temporal Modeling Techniques (Mahmood/Jennifer)
  - [x] Timeline (Mahmood)
- [x] Dashboard Discussion (20 min)
- [x] Modeling Discussion (20 min)
- [x] Housekeeping: Alternative meeting time for next week (since Kayla is away)

### Dashboard Questions:
- [x] Is the current proposed design appropriate for the end users? 
  - A: Yes. Would be useful to add data table and data download features
- [x] Who are the end users for dashboard (level of technical expertise) ? 
  - A: Public audience, health professionals
- [x] Region levels: In addition to CHSA, which region levels might be most useful on the dashboard? (Health authority, HSDA, LHA?)
   - A: Work with most and least granular levels
   - Kayla can provide HA level to avoid problems with suppressed data at the CHSA level

### Modeling Questions:
- [x] We are considering a Bayesian spatio-temporal model for standardized incidence ratios (SIRs) - would this be a useful metric to look at?
  - Reference: https://www.paulamoraga.com/book-geospatial/sec-arealdatatheory.html#spatio-temporal-small-area-disease-risk-estimation
  - A: Look into only temporal smoothing models to avoid problems with suppressed geographical regions. Preferable to look at smoothing incidence rate rather than standardized rates
- [x] How to address missing (suppressed) data?  
  - A: Not an issue if we use temporal smoothing models
- [x] When can the gender data be expected?
  - A: Approximately May 18th (Week 3)

### Action Items:

- [ ] Identify appropriate temporal models and send relevant papers to OPHO team (Mahmood/Jennifer)
- [x] Data for HA level and gender from Kayla
- [x] Confirm next meeting date: Wednesday May 18, 11-12pm

**Comment by jessie14** [comment]
Dashboard Notes/ Action Items:
- [ ] Add tab for data table with button to download data
- [ ] Filter options for HA level or CHSA level
- [ ] BCCDC Dashboard good reference of technical level
