### ISSUE TITLE
Meeting Agenda for 2022-05-18

### ISSUE THREAD

**Issue by shyan0903** [bcgov/opho-cdr-shiny#17]
## Agenda Items:
- [x] Proposal Feedback (10 min)
- [x] Dashboard Discussion (25 min)
- [x] Modeling Discussion (25 min)
  - EDA with LOESS baseline model (Jenn)

### Dashboard Questions:
- [x] Feedback on current layout and features
  - leave out the unknown regions from filters
  - keep the map legend the same scale
- [x] Are the plots we have included useful? 

### Modeling Questions:
- [x] Does it make sense to average standardized rates and confidence intervals if we are aggregating multiple regions?
- Loess baseline model:
   - [x] Loess is a flexible model that captures trends well, but disadvantages include that CIs for the rates occasionally extend below 0 with rare diseases. The CIs are approximated using the t-distribution. Is this an acceptable trade-off?

### Action Items:
- [ ] Use word documents rather than pdf files for easier edits
- [ ] Decide the preferred format for the final report
- [ ] Always mention BC Chronic Disease Registry and clarify it is a derived data product
- [x] Confirm the preferred color scheme
- [x] Change gender to sex
- [x] Change disease names to full name with acronyms in brackets
- [x] Confirm what's should be shown on the data download page: keep geography column,
- [ ] TBD: Kayla visiting for our final presentation on June 16th; we presenting virtually/in-person if funding is available to the ophp team on the last Wednesday of June.

**Comment by kaylamclean** [comment]
Thanks again for the great meeting today! I just have a few comments:
- In the proposal and subsequent reports it's okay to use "CDR" instead of "Chronic Disease Registry" as long as it's defined once
- We do not want cells with numerator <= 5 to be viewable or downloadable on the data/download tab
- It's preferable for our team to have the project presentation (in person or virtual) to the OPHO on June 22 (second to last Wed of June)
- Kayla still needs to confirm travel on June 16

**Comment by kaylamclean** [comment]
Hi again! I should also clarify what I meant by my first comment in the Executive Summary.

Current text:
"The Chronic Disease Registry is a data product that captures information about the rate of new and persistent
cases of chronic diseases in each CHSA (Community Health Service Area), as well as demographic information
such as sex and age standardized rates."

I would change this to something like:
"The BC Chronic Disease Registry (CDR) is a data product that captures information about the rate of new and persistent
cases of chronic diseases across the province. Age-standardized rates of disease are studied for different regions, including HAs (Health Authorities) and CHSAs (Community Health Service Areas), as well as for demographic variables such as sex."
